fix: remove metadata in descr in dtype_decode function. it fix gh-1152
zarr-developers/zarr-python pull request #1349
Opened 2023-02-12 08:54 UTC by ninousf

Remove metadata in dtype_decode function. It fixes gh-1152, because h5py puts metadata in dtypes which are not correctly managed in numpy

2023-02-12 09:04 UTC, joshmoore commented
Thanks for this, @ninousf. I've kicked off the workflows. A heads up that there look to be quite a few (unintended?) whitespace changes.

Also a question: do you think it would help to have access to h5py for testing?

2023-02-12 09:40 UTC, ninousf commented
sorry, the spaces are because i use yapf. 
h5py can be useful for tests, i think there are many cases where scientists use both formats and convert h5 to zarr and vice-versa

2023-03-09 09:07 UTC, joshmoore requested changes
> sorry, the spaces are because i use yapf.

Can you revert them or open a new PR to simplify review?

> h5py can be useful for tests, i think there are many cases where scientists use both formats and convert h5 to zarr and vice-versa

:+1: If you want to try it in this PR, feel free by adding it to https://github.com/zarr-developers/zarr-python/blob/main/requirements_dev_optional.txt; otherwise we can look into this as a follow-up.

2023-03-15 14:40 UTC, joshmoore commented on zarr/meta.py
> +        print('before', d)
Happy to, but independently I think we should get this green to know that it's stable beforehand, no?

2023-03-18 09:54 UTC, closed without merging