Remove zstandard dependency in favor of numcodecs
zarr-developers/zarr-python pull request #1838
Opened 2024-05-05 20:14 UTC by normanrz

I added `zstandard` as a dependency because the `zstd` in numcodecs doesn't expose the `checksum` config. This will be introduced in https://github.com/zarr-developers/numcodecs/pull/519. Once that PR is merged, we can use the numcodecs version.

2024-05-08 20:08 UTC, mkitti commented
The correct default level should be `0` which will then allow the Zstd C library to use the default setting according to how it was built:
https://github.com/facebook/zstd/blob/97291fc5020a8994019ab76cf0cda83a9824374c/lib/zstd.h#L338

2024-05-08 20:11 UTC, mkitti requested changes
At this level the default should stay `0` which the Zstandard C library will interpret as use the default that was built with as defined by zstd.h:
https://github.com/facebook/zstd/blob/97291fc5020a8994019ab76cf0cda83a9824374c/lib/zstd.h#L338

2024-05-08 20:11 UTC, mkitti commented on src/zarr/codecs/zstd.py
> +DEFAULT_ZSTD_LEVEL = 3
```suggestion
DEFAULT_ZSTD_LEVEL = 0
```

2024-05-08 20:11 UTC, mkitti commented on src/zarr/codecs/zstd.py
> +DEFAULT_ZSTD_LEVEL = 3
Here this should stay `0`. I'm not sure if we need this constant.

2024-07-22 16:11 UTC, normanrz commented
Now taht numcodecs 0.13 is out, we can move forward with this.

2024-08-11 11:25 UTC, merged