feature(typing): add py.typed file to package root
zarr-developers/zarr-python pull request #1935
Opened 2024-06-01 02:58 UTC by jhamman

This is an epic PR that I couldn't refrain from issuing myself... Sorry @dstansby 😉 !

2024-06-01 07:32 UTC, d-v-b approved these changes

2024-06-01 09:29 UTC, dstansby requested changes
I think it's worth fixing the rest of the `[[tool.mypy.overrides]]` sections in `pyproject.toml` first before adding this?

2024-06-01 15:36 UTC, jhamman commented
> sections

Happy to wait! We're not going to end up with a merge conflict here 😉

2024-06-02 10:46 UTC, dstansby approved these changes
:shipit:

2024-06-02 13:14 UTC, merged