[v3] fix: zarr v2 compatibility fixes for Dask
zarr-developers/zarr-python pull request #2186
Opened 2024-09-14 22:50 UTC by jhamman

- port normalize_chunks from v2
- add array.store property
- default to append in create

closes https://github.com/zarr-developers/zarr-python/issues/1953
xref: https://github.com/dask/dask/pull/11388

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

2024-09-14 22:59 UTC, jhamman commented on src/zarr/api/asynchronous.py
>      store_path = await make_store_path(store, mode=mode)
This logic could use a second thought. If the store is already instantiated with a `mode`, there is no need for a default. We should just make sure `mode is None` and that `read_only` is compatible with the state of the store.

2024-09-14 22:59 UTC, jhamman commented on src/zarr/core/array.py
> +        chunk_shape: ChunkCoords | None = None,  # TODO: handle bool and iterable of iterable types
In 2.x, we allowed additional types (`bool | tuple[tuple[int, ...], ...]`).

2024-09-14 22:59 UTC, jhamman commented on src/zarr/core/array.py
> +            raise ValueError("Only one of chunk_shape or chunks can be provided.")
I really don't like that we have both of these in the constructor. Seems like we can get away with only `chunks`.

2024-09-14 22:59 UTC, jhamman commented on src/zarr/core/array.py
> +        return self._async_array.store
We should also add these to `Group`

2024-09-14 22:59 UTC, jhamman commented on src/zarr/core/chunk_grids.py
> +        )  # TODO: check/error/warn for irregular chunks (e.g. if c[0] != c[1:-1])
except for this block, the rest of this function came from 2.x

2024-09-16 16:34 UTC, will-moore commented
Hi @jhamman - thanks for looking into this!
I tried to remember where I got to when I was looking into this before...

Here is what we're doing to load remote data with dask and  Zarr v2...
```
# dask==2023.5.0
# dask-image==2022.9.0
# zarr==2.18.2
import dask.array as da
from zarr import Array, Group, open
from zarr.storage import FSStore
import json

url = "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr"
store = FSStore(url)
zattrs = json.loads(store.get(".zattrs"))
array_path = zattrs["multiscales"][0]["datasets"][0]["path"]
array_data = da.from_zarr(store, array_path)
print(array_data)
# dask.array<from-zarr, shape=(2, 236, 275, 271), dtype=uint16, chunksize=(1, 1, 275, 271), chunktype=numpy.ndarray>
```

With zarr v3 I'm not getting as far as opening with dask as I'm failing to access any remote data, using a couple of different approaches here (using zarr from this branch), both failing with exceptions noted below...

```
import zarr
from zarr.store import RemoteStore
import s3fs

url = "https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr"
store = RemoteStore(url)
# RuntimeError: Timeout context manager should be used inside a task
g = zarr.group(store = store)


s3 = s3fs.S3FileSystem(anon=True, client_kwargs={'endpoint_url': 'https://uk1s3.embassy.ebi.ac.uk'})
store = s3fs.S3Map(root='idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr', s3=s3, check=False)
# TypeError - only LocalStore or MemoryStore is supported
g = zarr.group(store = store)
```

Is there some other way that I can try to load remote data?

Many thanks,
  Will

2024-09-17 15:03 UTC, TomAugspurger commented
Thanks for trying this out @will-moore. Can you share the full traceback?

In the meantime, I would expect something like

```python
 g = zarr.open_group(store=zarr.store.RemoteStore("s3://idr", endpoint_url="http://uk1s3.embassy.ebi.ac.uk", anon=True), path="zarr/v0.4/idr0062A/6001240.zarr")
```

Can you let us know if that works? It doesn't for me, but I'm not sure if some network / authentication setup is required.

2024-09-17 15:45 UTC, jhamman commented on tests/v3/test_codecs/test_codecs.py
> +    #     )
```suggestion
```

2024-09-17 15:45 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
The biggest change in this PR concerns how we handle the `mode` parameter in the top level API. I've taken the position that if a user passes in a `Store` class, the mode parameter is not allowed. I'm open to relaxing this for cases where `Store.mode == mode`. 

This is complicated elsewhere in the legacy API where mode overlaps with  the`overwrite` and `exists_ok` parameters.

2024-09-17 15:45 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +        raise ValueError("store and mode cannot be specified at the same time")
```suggestion
        raise ValueError("mode cannot be set when store is already initialized")
```

2024-09-17 15:45 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +            raise ValueError("mode cannot be specified if store is a Store")
```suggestion
    if isinstance(store, Store | StorePath):
        if mode is not None:
            raise ValueError("mode cannot be set when store is already initialized")
```

2024-09-17 15:57 UTC, will-moore commented
That sample you tried there is zarr v2 data, and it also seemed to need `https` rather than `http`!
So this works for me on another machine, with `zarr==3.0.0a0`, reading both zarr v2 and v3 data:
```
store=zarr.store.RemoteStore("s3://idr", endpoint_url="https://uk1s3.embassy.ebi.ac.uk", anon=True)
g = zarr.open_group(store=store, path="share/ome2024-ngff-challenge/idr0048/9846151.zarr")
print('zarr v3 group', g)

g2 = zarr.open_group(store=store, path="zarr/v0.4/idr0062A/6001240.zarr", zarr_version=2)
print('zarr v2', g2)
```
gives me:
```
zarr v3 group Group(_async_group=<AsyncGroup Remote fsspec store: S3FileSystem , idr/share/ome2024-ngff-challenge/idr0048/9846151.zarr>)
zarr v2 Group(_async_group=<AsyncGroup Remote fsspec store: S3FileSystem , idr/zarr/v0.4/idr0062A/6001240.zarr>)
``

On my machine, I unfortunately get:
<details><summary>this error</summary>

```
    g = zarr.open_group(store=store, path="share/ome2024-ngff-challenge/idr0048/9846151.zarr")
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/api/synchronous.py", line 175, in open_group
    sync(
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/sync.py", line 92, in sync
    raise return_result
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/sync.py", line 51, in _runner
    return await coro
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/api/asynchronous.py", line 523, in open_group
    return await AsyncGroup.open(store_path, zarr_format=zarr_format)
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/group.py", line 150, in open
    zarr_json_bytes = await (store_path / ZARR_JSON).get()
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/store/core.py", line 35, in get
    return await self.store.get(self.path, prototype=prototype, byte_range=byte_range)
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/zarr/store/remote.py", line 98, in get
    await (
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 1128, in _cat_file
    return await _error_wrapper(_call_and_read, retries=self.retries)
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 145, in _error_wrapper
    raise err
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 1115, in _call_and_read
    resp = await self._call_s3(
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 358, in _call_s3
    await self.set_session()
  File "/Users/wmoore/opt/anaconda3/envs/zarr_v3/lib/python3.10/site-packages/s3fs/core.py", line 519, in set_session
    self.session = aiobotocore.session.AioSession(**self.kwargs)
TypeError: AioSession.__init__() got an unexpected keyword argument '//'
```
</details>

Which is an issue that seems to affect *just* me, as I already reported at https://github.com/ome/ome2024-ngff-challenge/issues/22 and I can't seem to fix on my machine, which is kinda annoying!
Might have to re-install anaconda, or try some other option...

Thanks for your help!

2024-09-18 14:07 UTC, TomAugspurger commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
FWIW, I'm hitting some... challenging behavior in xarray's tests around `store` objects and modes. Many of those tests roughly take the form

```python
store = create_my_store(...)
dataset.to_zarr(store, mode="w")
xr.open_dataset(store, mode="r")
```

The `store` arguments were typically "store-like" (dictionary, `pathlib.Path`) not concrete stores, but there are tests using the concrete `ZipStore`.

I was going to propose all the top-level APIs having `mode=None` and then allowing a user to specify `mode=mode` to "re-open" the `store` with that mode. I'm not sure if that's actually possible in general though. For something like a `MemoryStore`, the `readonly` check is a purely logical thing in the Zarr layer. But I can imagine store implementations where it'd be impossible to re-open a readonly store as writable. We could introduce an API for that, but that seems complicated.

2024-09-18 14:43 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
@d-v-b and I just spoke about this and agree that this is ... painful. 

Some options that we could consider:

- disallow passing `Store` type and `mode != None`. The only use for mode in the top level API is to create a store from a `str | Path` but existing stores use the mode they were given when they were instantiated. This PR implements this approach.
- we could develop an API for creating clones of stores. `Store.clone(mode: OpenMode)` would allow us to create a new store with a different open mode. As you say @TomAugspurger, this won't work equally well for all stores.  
- we could fall back to making `mode` a `Group | Array` attribute. We had good reason for changing this but if its the only way to get the API compatibility back, we could consider it.

2024-09-25 16:46 UTC, TomAugspurger commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
https://github.com/zarr-developers/zarr-python/pull/2249 is a POC for `Store.clone` (which I called `Store.with_mode`)

2024-09-29 22:24 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
```suggestion
    store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
```suggestion
    store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
```suggestion
    store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
```suggestion
    store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    ):  # FIXME: apply path before opening store in w or risk deleting existing data
```suggestion
    if path is not None:
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/core/array.py
> +    print("path", node.store_path.path)
```suggestion
```

2024-09-29 22:24 UTC, jhamman commented on src/zarr/core/array.py
> +    ]
@TomAugspurger - this was needed to enable `zarr.create(store={}, path="a")` such that the root `zarr.json` is created in addition to `a/zarr.json`.

2024-09-30 13:07 UTC, d-v-b requested changes

2024-09-30 13:40 UTC, jhamman commented on src/zarr/api/asynchronous.py
> +    store_path = await make_store_path(store, mode=mode)
```suggestion
    store_path = await make_store_path(store, mode=mode, storage_options=storage_options)
```

2024-09-30 13:42 UTC, jhamman commented on src/zarr/core/array.py
> +        chunks: ShapeLike | None = None,  # TODO: handle bool and iterable of iterable types
```suggestion
        chunks: ShapeLike | None = None,
```

2024-09-30 20:11 UTC, jhamman commented on src/zarr/core/array.py
> +            raise ValueError("Only one of chunk_shape or chunks can be provided.")
I want that to get sorted out elsewhere.

2024-09-30 21:37 UTC, jhamman commented on tests/v3/test_codecs/test_codecs.py
> -    spath = StorePath(store, "invalid_metadata")
The context here is that this example no longer creates invalid metadata: 

```
In [1]: import zarr

In [2]: a = zarr.create(shape=(16, 16, 16), chunk_shape=(16, 16))

In [3]: a.chunks
Out[3]: (16, 16, 16)
```

2024-10-01 02:36 UTC, d-v-b approved these changes
good to go i think

2024-10-01 14:10 UTC, TomAugspurger approved these changes
Looks good, just a couple minor things.

2024-10-01 14:10 UTC, TomAugspurger commented on src/zarr/core/array.py
> +            logger.debug("Ensure parents: %s", parents)
Do we want to keep this?

2024-10-01 14:10 UTC, TomAugspurger commented on src/zarr/core/array.py
> +    if not path:
Do you know whether this branch is covered by an existing test? If not, it might be good to add one.

2024-10-01 14:43 UTC, jhamman commented on src/zarr/core/array.py
> +
```suggestion
```

2024-10-01 15:00 UTC, merged