Add docstrings for array module
zarr-developers/zarr-python pull request #2281
Opened 2024-10-01 14:20 UTC by MSanKeys963

xref: #2215 and #2245 

This PR adds docstrings for `zarr.array` module and builds on top of @e-marshall's #2276. I've added documentation for following functions:

- _create_v3()
- _create_v2()
- from_dict()
- _get_selection()
- getitem()
- _set_selection()
- setitem()
- resize()
- update_attributes()

I will start adding code examples soon. Feedback on the current draft would be greatly appreciated. Thanks!

2024-10-01 14:21 UTC, MSanKeys963 commented
pre-commit.ci autofix

2024-10-15 22:59 UTC, jhamman commented
@MSanKeys963 - we just merged @e-marshall's PR so you can update this one and finish it off. 

I think you can also skip docstrings for any method that start with `_`. So that should help limit the scope here.

2024-10-19 18:45 UTC, MSanKeys963 commented
Please review, @jhamman — my apologies for the delay.

2024-11-06 06:02 UTC, jhamman requested changes
Thanks for pushing on this @MSanKeys963. A few minor suggestions but it mostly looks good.

2024-11-06 06:02 UTC, jhamman commented on src/zarr/core/array.py
> +        new_attributes : dict of str to JSON
```suggestion
        new_attributes : dict
```

2024-11-08 15:53 UTC, jhamman approved these changes

2024-11-08 16:11 UTC, merged