Slim dependencies
zarr-developers/zarr-python pull request #2395
Opened 2024-10-17 16:52 UTC by jhamman

This PR implements the main ideas from #2391, removing `crc32c` and `fsspec` as core dependencies and adding them to the `sharding` and `remote` groups respectively. Imports are adjusted in minor ways and we now take advantage of `pytest.importorskip` in a few new places.

TODO: if we decide to go this route, we should have a separate part of the test matrix that includes optional dependencies.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

2024-10-18 10:09 UTC, dstansby requested changes
I think we're coming to a consensus in https://github.com/zarr-developers/zarr-python/issues/2391 (?) of
- Move dependency of `crc32c` to numcodecs (https://github.com/zarr-developers/numcodecs/issues/610)
- Make `fsspec` optional

For the second one, would be good to add some docs explaining how to install the `remote` extra, and what functionality it enables.

2024-10-18 13:09 UTC, jhamman commented on pyproject.toml
> +remote = [
```suggestion
fsspec = [
```

2024-10-21 20:24 UTC, jhamman commented
Something I learned over the weekend is that `crc32c` is LGPL Licensed. Regardless of whether we get `crc32c` into `numcodecs`, we may want to pick a different implementation ([googleapis/python-crc32c](https://github.com/googleapis/python-crc32c) is Apache 2.0 licenced).

2024-11-13 06:18 UTC, jhamman commented on pyproject.toml
> +    'donfig>=0.8.1',
```suggestion
    'donfig>=0.8.1',
    'crc32c',
```

2024-11-13 06:19 UTC, jhamman commented on pyproject.toml
> +]
```suggestion
```

2024-12-05 05:05 UTC, closed without merging