docs: split tutorial into multiple user guide sections
zarr-developers/zarr-python pull request #2589
Opened 2024-12-29 21:44 UTC by jhamman

This PR updates Zarr's documentation to include a new multi-page user-guide, in-place of the prior single page tutorial.

Notes for reviewers:

- This was split off from https://github.com/zarr-developers/zarr-python/pull/2568
- Most content remains unchanged from the tutorial, despite the large diff line count. Some new sections were added in 2568. The only net new section added was config.rst.
- Examples now use the Ipython sphinx directive

2024-12-30 10:52 UTC, dstansby reviewed
Liking the new sections, makes it much easier to read than the old tutorial 👍 

A couple of major questions:

The "copying/migrating data" tutorial section wasn't migrated from the old tutorial, is this intentional?

For IPython, what was the motivation for switching to this from doctests? As it stands it has a few major drawbacks:
1. Trying to copy/paste a block of code doesn't work, because it selects the `Out[...]` text too:
![Screenshot 2024-12-30 at 10 07 54](https://github.com/user-attachments/assets/6ff0f7dc-7ecc-49c5-9fe8-f6c5fa205bdc)
2. The expected output isn't embedded any more. This gave us another layer of regression tests when we ran the tutorial as a doc test, and on top of making sure the code runs, made sure the output was as expected.
3. I find having a line break between each line of code makes it much less readable - old vs new:
![Screenshot 2024-12-30 at 10 52 17](https://github.com/user-attachments/assets/0d157ab1-5c28-4061-8de6-11fde25b56f8)
![Screenshot 2024-12-30 at 10 51 24](https://github.com/user-attachments/assets/6ec427fe-2a98-43b7-baa5-f3ae7ef99258)

Is it possible to fix these with new IPython plugin?

Finally, what's the plan for all the TODOs (especially the numcodecs and Sharding bits, and configuring blosc)? To do them in another PR before 3.0? If so would be good to open issues for these so they're not lost and released as TODOs in 3.0

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/arrays.rst
> +Working with Arrays
```suggestion
Working with arrays
```
To match other titles of guide pages

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/storage.rst
> +.. _tutorial_storage:
```suggestion
.. _guide_storage:
```

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/storage.rst
> +   # implicitly create a writable LocalStore
```suggestion
   # Implicitly create a writable LocalStore
```

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/storage.rst
> +   # implicitly create a read-only FsspecStore
```suggestion
   # Implicitly create a read-only FsspecStore
```

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/storage.rst
> +   # implicitly creates a MemoryStore
```suggestion
   # Implicitly creates a MemoryStore
```

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/storage.rst
> +that implements the `AbstractFileSystem` API. ``storage_options`` can be used to configure
```suggestion
that implements the `AbstractFileSystem` API. ``storage_options`` can be used to configure
```
The AbstractFileSystem link here isn't working

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/consolidated_metadata.rst
> +Zarr-Python implements the `Consolidated Metadata`_ extension to the Zarr Spec.
If I search fo "consolidated" on this link it doesn't turn up with anything - can this be fixed to link to a more suitable place than the zarr spec itself, which doesn't mention consolidated metadata?

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/consolidated_metadata.rst
> +   :okwarning:
There aren't any warnings showing up in the built docs, can this be removed?

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/v3_todos.rst
I don't think there's much value in having code for features that don't work in the docs. I'd suggest delete all the examples, have a short bullet point list of the missing features, and then link out to the relevant tutorial section in the v2 docs. This should also make it easier to see what's missing at a glance.

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/performance.rst
> +   In [144]: rm -r data/
```suggestion
   rm -r data/
```

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/performance.rst
> +.. .. ipython:: python
Is there a reason these blocks of code aren't being run?

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/performance.rst
> +~~~~~~~~~~~~~~~~~
The heading level is wrong here, I don't think this is meant to be under "Pickle support"

2024-12-30 10:52 UTC, dstansby commented on pyproject.toml
> +    'pickleshare',
```suggestion
```
This doesn't seem to be used

2024-12-30 10:52 UTC, dstansby commented on pyproject.toml
> +    'msgpack',
```suggestion
``` 
This is already included in the line above

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/index.rst
> +    whatsnew_v3
It doesn't feel right for a what's new page to be under Advanced topics - perhaps under a new "Zarr v3" section instead, which can also have the migration guide and TODOs pages?

2024-12-30 10:52 UTC, dstansby commented on docs/user-guide/config.rst
> +.. code-block:: python
This should be an IPython block to be consistent

2024-12-30 10:54 UTC, dstansby commented on docs/user-guide/arrays.rst
> +   store = {}
Never mind - this seems like the best way to do this.

2025-01-01 14:32 UTC, jhamman commented on docs/user-guide/index.rst
> +    whatsnew_v3
I'd like to do away with this page in favor a single change log page. Can we do that in a follow up PR?

2025-01-01 14:34 UTC, jhamman commented on docs/user-guide/consolidated_metadata.rst
> +   :okwarning:
I believe this silences warnings. I'll try removing it but if we should expect a warning when `consolidate_metadata` is used on v3 stores.

2025-01-01 14:54 UTC, jhamman commented
Thanks for the review @dstansby! 

> Liking the new sections, makes it much easier to read than the old tutorial 👍
> 
> A couple of major questions:
> 
> The "copying/migrating data" tutorial section wasn't migrated from the old tutorial, is this intentional?

We have not implemented `copy`, `copy_all`, and `copy_store` yet. I'll add these to the list of TODOs in the migration guide if they are not there already.

> For IPython, what was the motivation for switching to this from doctests? 

For one, we weren't using the doc tests! Beyond that, this isn't something I feel super strong about. We've had a lot of success using the Ipython directive in the Xarray project.

As it stands it has a few major drawbacks:
> 1. Trying to copy/paste a block of code doesn't work, because it selects the `Out[...]` text too:

Not true if you use the copy button, example below: 

```python
z1[:] = 42

z1[0, :] = np.arange(10000)

z1[:, 0] = np.arange(10000)
```

I think there is probably a way to further configure the style.

> 2. The expected output isn't embedded any more. This gave us another layer of regression tests when we ran the tutorial as a doc test, and on top of making sure the code runs, made sure the output was as expected.

We can insert assertions in hidden cells as desired. This would achieve the same thing.

> 3. I find having a line break between each line of code makes it much less readable - old vs new:
>
> Is it possible to fix these with new IPython plugin?

Likely yes. Can we iterate on the styling after this first PR goes in?
> 
> Finally, what's the plan for all the TODOs (especially the numcodecs and Sharding bits, and configuring blosc)? To do them in another PR before 3.0? If so would be good to open issues for these so they're not lost and released as TODOs in 3.0

I'm waiting #2463. I have a branch combining these but I'll need to start it over now that I've split up the docs refactor. So yes, let's do them in another PR.

2025-01-01 15:52 UTC, jhamman commented on docs/user-guide/arrays.rst
> +storage, see the :ref:`tutorial_storage` guide for more details.
done.

2025-01-01 15:52 UTC, jhamman commented on docs/user-guide/arrays.rst
> +       store='data/example-2.zarr',
changed the text below

2025-01-01 15:53 UTC, jhamman commented on docs/user-guide/arrays.rst
> +
done.

2025-01-01 15:53 UTC, jhamman commented on docs/user-guide/arrays.rst
> +Zarr arrays support a similar interface to `NumPy <https://numpy.org/doc/stable/>`
fixed (missing the trailing _)

2025-01-01 15:53 UTC, jhamman commented on docs/user-guide/arrays.rst
> +For a complete list of array creation routines see the :mod:`zarr.api.synchronous`
done.

2025-01-01 15:55 UTC, jhamman commented on docs/user-guide/arrays.rst
> +   )
Possible but I'm going to leave this for later. We'd have to go back to an array from a ways up the guide.

2025-01-01 15:57 UTC, jhamman commented on docs/user-guide/arrays.rst
> +   z.info_complete()
done.

2025-01-01 15:59 UTC, jhamman commented on docs/user-guide/arrays.rst
> +Working with Arrays
done (and for a few other pages)

2025-01-01 16:01 UTC, jhamman commented on docs/user-guide/storage.rst
> +that implements the `AbstractFileSystem` API. ``storage_options`` can be used to configure
fixed.

2025-01-01 16:08 UTC, jhamman commented on docs/user-guide/consolidated_metadata.rst
> +Zarr-Python implements the `Consolidated Metadata`_ extension to the Zarr Spec.
Fixed. + added a warning about the lack of an accepted extension to the spec.

2025-01-01 16:09 UTC, jhamman commented on docs/user-guide/performance.rst
> +~~~~~~~~~~~~~~~~~
fixed.

2025-01-01 16:14 UTC, jhamman commented on docs/user-guide/config.rst
> +.. code-block:: python
done.

2025-01-01 22:07 UTC, dstansby commented on docs/user-guide/index.rst
> +    whatsnew_v3
👍 can definitely save this for a follow up PR (maybe one of the other open ones). I think it's worth having a slighlty more fleshed out "what's new in v3" guide that's more explain-y than a changelog would be though (which is what this page currently does very well)

2025-01-01 22:18 UTC, dstansby commented
>>  Trying to copy/paste a block of code doesn't work, because it selects the Out[...] text too:

> Not true if you use the copy button

This isn't a solution if you want to select two lines of code from a longer block.

>> This gave us another layer of regression tests when we ran the tutorial as a doc test, and on top of making sure the code runs, made sure the output was as expected.

> We can insert assertions in hidden cells as desired. This would achieve the same thing.

But with a much higher maintenance burden I think? We would have to manually concoct a hidden assertion for every code block in this case, whereas with the doctests we can just generate all the output automatically.


So given there don't seem to be any benefits to using the IPython plugin, but there still seem to be drawbacks to me, I'd say we should keep existing code block style for now.

re. the TODOs, I'm a bit tired to do it now but tomorrow I can open issues to keep track of them (if you haven't already).

2025-01-01 22:42 UTC, jhamman commented
My view is that the most important thing is to have documentation that actually runs! I'm happy to hand this off to someone with sufficient experience with doctests (maybe @dstansby) but that isn't me. If no one is volunteering to do it right now, I'm going to press forward with this solution and we can revisit when someone else has time/energy for another doctest effort. I'll also note that these aren't mutually exclusive concepts (reading up on the ipython extension is [worthwhile](https://ipython.readthedocs.io/en/stable/sphinxext.html))

2025-01-02 06:04 UTC, jhamman commented on docs/user-guide/arrays.rst
> +   blosc.list_compressors()
this is relevant for Zarr v2 arrays. We will rev this section after #2463 goes in.

2025-01-02 11:13 UTC, dstansby commented
In order to keep this moving, lets drop the switch to using the IPython plugin, since that shouldn't block a v3 release.

2025-01-02 11:18 UTC, dstansby requested changes
Marking as request changes to revert the IPython change. @jhamman I'd be happy to change the code snippets in code back, but don't want to push to your PR without permission - let me know either way.

2025-01-02 14:28 UTC, jhamman commented
If you can update the code snippets today, feel free to push to this branch. I'm all checked in. Like I said above, I'm not planning on reverting the change myself though.

2025-01-02 18:29 UTC, normanrz commented
> I think it's a reasonable ask to revert the change though, and not merge before it's reverted.

To be honest, I think it is more important to merge this PR because of the dependent PRs. I feel this is blocking our progress right now. We can change away from IPython at any later point in time.

2025-01-02 18:38 UTC, d-v-b commented
> > I think it's a reasonable ask to revert the change though, and not merge before it's reverted.
> 
> To be honest, I think it is more important to merge this PR quickly because of the dependent PRs. I feel this is blocking our progress right now. We can change away from IPython at any later point in time.

+1 to this, lets get this PR in and sort out doctest / ipython later

2025-01-02 18:40 UTC, dcherian commented
I concur. Working doc examples are very valuable!

2025-01-02 18:57 UTC, dstansby commented
I'm sorry, but I really want to insist we don't merge this with IPython in it, because it's a change has demonstratable downsides. On a point of principle, just opening a large PR shouldn't come with an assumption that it's going to get merged without engaging with review (if nothing else, it's not particularly respectable of the reviewers time). On a practical point, I spent about an hour sorting this out at https://github.com/zarr-developers/zarr-python/pull/2623 today. So 🙏 can folks review and merge https://github.com/zarr-developers/zarr-python/pull/2623 into this PR first.

2025-01-02 19:48 UTC, d-v-b commented
> So 🙏 can folks review and merge #2623 into this PR first.

If the main value-add from the ipython plugin is that it ensures that the docs contain the output of current code, then an alternative to that plugin should achieve the same goal. It seems like #2623 doesn't have the doctests running for the current codebase, so that PR isn't really a replacement for the ipython plugin.

2025-01-02 19:51 UTC, d-v-b commented
to be clear, I don't like the style of the ipython output either, and if we can't make lines of code copy + pasteable with the ipython plugin then we should _asymptotically_ move to doctests. But we kind of need docs _today_ (or yesterday :) ) that reflect what the code does _today_, and the ipython plugin seems expedient for that.

2025-01-02 20:06 UTC, dstansby commented
I'm not arguing that IPython isn't valuable - just that introduces downsides, and because it seems to need more discussion we should stick with the status quo which is doctests to avoid holding up v3.

2025-01-02 20:15 UTC, d-v-b commented
> the status quo which is doctests, to avoid holding up v3.

admittedly I'm late to this discussion, but my impression was that the status quo was that the doctests were not actually getting run, resulting in stale example code in the docs. I don't think anyone wants that. 

So the next question is, how can we ensure that the docs contain real examples? Either we make the doctests work, or we use another strategy, e.g. running code when we build the docs (the ipython directive). Given the current context, we should do whichever of these two is most expedient, in the interest of moving things forward -- the most important thing is that the generated docs are _correct_. This allows everyone to hack on the docs productively. IMO, the only thing that should block that part of this PR is a functionally equivalent solution to the problem solved with the ipython directive. Does that make sense?

2025-01-02 20:16 UTC, dstansby commented
> admittedly I'm late to this discussion, but my impression was that the status quo was that the doctests were not actually getting run, resulting in stale example code in the docs. I don't think anyone wants that.

👍 , which is why I fixed them in https://github.com/zarr-developers/zarr-python/pull/2623...

2025-01-02 20:20 UTC, jhamman commented
Let's deescalate this a bit.

If we can't get the doctests pr passing with ci today, we can merge this as is (with ipython) and go back to doctests as soon as it's ready.

I'm hearing general agreement that this PR is directionally aligned with where we want to go. Let's continue to iterate but in a non blocking way. 

@dstansby - I know this isn't your ideal but I think it's what is best for the project overall.

2025-01-02 20:30 UTC, dstansby commented
Okay, quick update, I'm trialling enabling doctests at https://github.com/zarr-developers/zarr-python/pull/2626, which I *think* I have working. If it works, that PR should fail, and then I'll close and merge into https://github.com/zarr-developers/zarr-python/pull/2623. Sorry it's a bit complex, but avoids me messing around with GH actions config in https://github.com/zarr-developers/zarr-python/pull/2623 to get the tests running...

2025-01-02 23:22 UTC, dstansby commented
Quick update, I've:

- added a new doctests CI run (was much simpler than running doctests in all the existing test runs)
- added a new hatch environment that can be used to run the doctests (hatch run doctest:run) or automatically fix the output if it changes (hatch run doctest:fix)

Some of the doctests need fixing because of https://github.com/zarr-developers/zarr-python/pull/2463 being merged, but hopefully the new CI job and hatch env make that a lot easier for someone else to do.

2025-01-03 09:58 UTC, dstansby requested changes
Doctests need fixing - otherwise I think this is 👍

2025-01-03 10:51 UTC, normanrz commented
> Doctests need fixing - otherwise I think this is 👍

Working on it.

2025-01-03 14:30 UTC, dstansby approved these changes
LGTM 🚢  - a couple of optional comments. I haven't reviewed any of the actual content this time.

2025-01-03 14:30 UTC, dstansby commented on docs/user-guide/consolidated_metadata.rst
> +   >>> from pprint import pprint
I think worth showing this and importing it where it's used instead of hiding it away at the top, so users trying to run the code know where the `pprint` command is coming from?

2025-01-03 14:30 UTC, dstansby commented on tests/test_tree.py
> +    os.environ["OVERRIDE_COLOR_SYSTEM"] = "truecolor"
Just out of interest, why's this needed?

2025-01-03 14:31 UTC, merged

2025-01-03 14:40 UTC, normanrz commented on tests/test_tree.py
> +    os.environ["OVERRIDE_COLOR_SYSTEM"] = "truecolor"
`test_tree.py` expects the tree to be rendered with the control sequences for text formatting (e.g. bold font). However, by default `rich` doesn't include that when running within pytest, because it detects that it is not running in a real terminal as the output is captured by pytest. This overrides the behavior in `rich`. This issue only surfaced now, because I added `rich` to the test dependencies and therefore `test_tree.py` wasn't skipped anymore.
https://github.com/zarr-developers/zarr-python/blob/main/tests/test_tree.py#L31-L54

2025-01-03 14:52 UTC, normanrz commented on docs/user-guide/consolidated_metadata.rst
> +   >>> from pprint import pprint
See #2632