docs: add new top level about page
zarr-developers/zarr-python pull request #2592
Opened 2024-12-29 22:16 UTC by jhamman

This PR adds a new `about` page to Zarr's documentation. 

Notes for reviewers:

- This was split out from https://github.com/zarr-developers/zarr-python/pull/2568 and builds on https://github.com/zarr-developers/zarr-python/pull/2589.
- This content was previously part of the `getting-started` page which is turning into the `quickstart` page in #2590.

2024-12-30 11:36 UTC, normanrz approved these changes

2024-12-30 16:58 UTC, dstansby requested changes
Shouldn't this content be removed from the getting started page at the same time?

2025-01-01 21:38 UTC, jhamman commented
> Shouldn't this content be removed from the getting started page at the same time?

I'm trying to avoid merge conflicts with #2590 which replaces the getting started page with a new quickstart page.

2025-01-01 22:20 UTC, dstansby commented
Given the whole of getting started is deleted in https://github.com/zarr-developers/zarr-python/pull/2590, that would be a pretty simple merge/rebase conflict to address if it came up no?

2025-01-02 15:02 UTC, dstansby approved these changes

2025-01-02 15:03 UTC, merged