docs: consolidate developer docs + update contributing page for v3
zarr-developers/zarr-python pull request #2593
Opened 2024-12-29 22:28 UTC by jhamman

This PR replaces consolidates Zarr's developer docs under the `/developers` route, the included pages are:

- `contributing`
- `release`
- `roadmap`

Notes for reviewers:

- This was split out from https://github.com/zarr-developers/zarr-python/pull/2568 and builds on https://github.com/zarr-developers/zarr-python/pull/2589.
- Redirects were added to avoid breaking links
- More effort could be spent on the developer guide if someone has time.

2024-12-30 11:44 UTC, normanrz approved these changes

2024-12-30 11:44 UTC, normanrz commented on docs/developers/contributing.rst
> +should run and pass as doctests under Python 3.10.
```suggestion
should run and pass as doctests under Python 3.11.
```

2024-12-30 16:56 UTC, dstansby requested changes
👍, but doc build needs fixing, and I left some other minor fixes inline too

2024-12-30 16:56 UTC, dstansby commented on docs/developers/contributing.rst
> +2. An explanation of why the current behavior is wrong/not desired, and what you
Boo for 🇺🇸 spelling 😉 . My serious thought here (not for this PR), is can we configure codespell to enforce EN-US instead of EN-GB?

2024-12-30 16:56 UTC, dstansby commented on docs/developers/contributing.rst
> +(currently Python 3.12). Both unit tests and docstring doctests are included when computing
```suggestion
Both unit tests and docstring doctests are included when computing
```
Latest stable Python is 3.13, but I'd just get rid of this to save having to update it every new release

2024-12-30 16:56 UTC, dstansby commented on docs/developers/contributing.rst
> +    $ hatch --env docs run build
Hmm, this doesn't work for me:

```
% hatch --env docs run build
sphinx-build -b html -d _build/doctrees  -W --keep-going . _build/html
/Users/dstansby/Library/Application Support/hatch/env/virtual/zarr/4XDzdpBV/docs/bin/sphinx-build: line 2: /Users/dstansby/Library/Application Support/hatch/env/virtual/zarr/4XDzdpBV/docs/bin/python: No such file or directory
/Users/dstansby/Library/Application Support/hatch/env/virtual/zarr/4XDzdpBV/docs/bin/sphinx-build: line 2: exec: /Users/dstansby/Library/Application Support/hatch/env/virtual/zarr/4XDzdpBV/docs/bin/python: cannot execute: No such file or directory
make: *** [html] Error 126
```

Would be good to either:
- Fix in this PR
- Change back to the old instructions (which at least seem to work for me with the right deps installed) and open an issue to update this later

2025-01-01 22:06 UTC, jhamman commented on docs/developers/contributing.rst
> +2. An explanation of why the current behavior is wrong/not desired, and what you
This was my editor being greedy. I've changed it back. If we want to enforce one or the other, I'm happy either way.

2025-01-01 22:09 UTC, jhamman commented on docs/developers/contributing.rst
> +    $ hatch --env docs run build
Huh! This is working fine for me. 

```
❯ hatch --env docs run build
sphinx-build -b html -d _build/doctrees  -W --keep-going . _build/html
Running Sphinx v8.1.3
loading translations [en]... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
loading pickled environment... The configuration has changed (6 options: 'html_js_files', 'html_permalinks_icon', 'html_static_path', 'html_theme_options', 'redirects', ...)
done
[autosummary] generating autosummary for: _autoapi/zarr/abc/codec/index.rst, _autoapi/zarr/abc/index.rst, _autoapi/zarr/abc/metadata/index.rst, _autoapi/zarr/abc/store/index.rst, _autoapi/zarr/api/asynchronous/index.rst, _autoapi/zarr/api/index.rst, _autoapi/zarr/api/synchronous/index.rst, _autoapi/zarr/codecs/blosc/index.rst, _autoapi/zarr/codecs/bytes/index.rst, _autoapi/zarr/codecs/crc32c_/index.rst, ..., index.rst, installation.rst, user-guide/arrays.rst, user-guide/attributes.rst, user-guide/config.rst, user-guide/consolidated_metadata.rst, user-guide/groups.rst, user-guide/index.rst, user-guide/performance.rst, user-guide/storage.rst
[AutoAPI] Reading files... [100%] /Users/jhamman/Library/CloudStorage/Dropbox/src/zarr-python/src/zarr/api/__init__.py
[AutoAPI] Mapping Data... [100%] /Users/jhamman/Library/CloudStorage/Dropbox/src/zarr-python/src/zarr/api/__init__.py
[AutoAPI] Rendering Data... [  2%] zarr
[AutoAPI] Rendering Data... [  4%] zarr.abc
[AutoAPI] Rendering Data... [  5%] zarr.api
[AutoAPI] Rendering Data... [  7%] zarr.core
...
```

If others are having issues here, let's figure out why.

2025-01-01 22:21 UTC, dstansby commented on docs/developers/contributing.rst
> +2. An explanation of why the current behavior is wrong/not desired, and what you
Ah sorry if it wasn't clear that I wasn't bothered about this change, just thinking out loud 😄

2025-01-01 22:32 UTC, dstansby commented on docs/developers/contributing.rst
> +    $ hatch --env docs run build
I just cleaned out my venvs and went again, and seems to be working 👍 I'll open a issue if it comes up again as an issue for me in the future.

2025-01-02 21:05 UTC, dstansby commented
Shouldn't be merged with doc build failing, but I've dismissed my review so it's not blocking someone else from reviewing and merging

2025-01-04 00:31 UTC, merged