docs: add migration page to user guide
zarr-developers/zarr-python pull request #2596
Opened 2024-12-29 23:07 UTC by jhamman

This PR adds a page describing the migration process for users upgrading to zarr 3.0.

Notes for reviewers:

- This was split out from https://github.com/zarr-developers/zarr-python/pull/2568 and builds on https://github.com/zarr-developers/zarr-python/pull/2589. Initially started in #2102.

2024-12-30 11:41 UTC, dstansby requested changes
This is a good start, but I think needs some major improvements and additions. In particular: 

- Removing the "getting ready" section, since there won't be a decent period of time between these docs existing and the final release for folks to prepare for v3.
- Being more explicit about what's change and how to adapt existing code (I left inline comments for this)
- Listing where keyword only arguments have been introduced (e.g., I noticed these in [zarr.create](https://zarr.readthedocs.io/en/latest/_autoapi/zarr/index.html#zarr.create)), as this is a major breaking change where users will have to update code

I also compared the v2 and v3 API, and there's some major additions that need making to this guide so users can migrate:
- Explaining how to adapt code that previously used [zarr.hierarchy](https://zarr.readthedocs.io/en/stable/api/hierarchy.html)
- Explaining how to migrate code that uses functions in [zarr.storage](https://zarr.readthedocs.io/en/stable/api/storage.html) that no longer exist in v3
- Explaining what the alternative to [zarr.n5](https://zarr.readthedocs.io/en/stable/api/n5.html) is
- Explaining how to update code that imports from [zarr.codecs](https://github.com/zarr-developers/zarr-python/blob/support/v2/zarr/codecs.py)
- Explaining how to update code that uses [zarr.attrs](https://zarr.readthedocs.io/en/stable/api/attrs.html)
- Explaining how to update code that uses [zarr.sync](https://zarr.readthedocs.io/en/stable/api/sync.html)

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  cloud object store)
```suggestion
Zarr-Python 3 represents a major refactor of the Zarr-Python codebase. Some of the
goals motivating this refactor included:

* adding support for the Zarr V3 specification (alongside the Zarr V2 specification)
* cleaning up internal and user facing APIs
* improving performance (particularly in high latency storage environments like
  cloud object store)
  
To accomodate this, Zarr-Python 3.0 introduces a number of changes to the API, including a number
of significant breaking changes and pending deprecations.

This page provides a guide highlighting the most notable changes to help you
migrate your code from version 2 to version 3.
```
I think this is a more logical order, which motivates the changes first.

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +major version update), but we have attempted to maintain ~95% backwards compatibility
```suggestion
major version update), but where poissible we have maintained backwards compatibility
```

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +Ahead of the 3.0 release, we suggest projects that depend on Zarr-Python take the
If the plan is to release in 6 days time, then I don't think there's much point adding a new section to the docs that says "Ahead of the 3.0 release...". I'd suggest moving the "Using zarr Python v2" section up here, and adding the pinning advice to that section. Then the flow is

1. How to continue using v2
2. How to transition to v3

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +1. Disallow direct construction - use :func:`zarr.open_array` or :func:`zarr.create_array`
It's not clear here whether direct contstruction is:

- No longer possible
- Deprecated
- Possible, but discouraged

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +2. Deprecated most of the h5py compatibility methods. The following migration is suggested:
```suggestion
2. Most of the h5py compatibility methods are deprecated. The following migration is suggested:
```

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +2. Deprecated most of the h5py compatibility methods. The following migration is suggested:
Are the suggested functions drop in replacements with the same arguments? If not, can we provide a clearer guide on how to translate existing calls to create_dataset/require_dataset to create_array/require_array?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +2. Switched to a primarily Async interface.
What does this mean in conrete terms for a user? Is it just a behind the scenes change (if so, why was it done? what benefits does it bring?), or does the user have to adapt their code for this change?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +Beyond the changes store interface, a number of deprecated stores were also removed in Zarr-Python 3:
What are we recommending users who use these stores do? Create their own custom stores? Or migrate to other options?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +Dependencies Changes
```suggestion
Dependency Changes
```

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +
```suggestion

When installing using `pip`:
```
Since this doesn't apply to conda installs.

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
I think this should be in a what's new, not a migration guide, since there's no functionality from v2 in this section.

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +- The keyword argument ``zarr_version`` has been deprecated in favor of ``zarr_format``.
What functions is this an argument to?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +- The following options in the top-level API have not been ported to Zarr-Python 3 yet.
What does "options in the top-level API" mean? Config options? Or arguments (and if so, to which functions?)

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +- The following features have not been ported to Zarr-Python 3 yet:
Do we want folks to open github issues if they want these features too?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  If these options are important to you, please open a
Perhaps move this request for issues up to the top of this section, so it applies to all the bullet points and not just this one?

2024-12-30 11:41 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +migrate your code from version 2 to version 3.
```suggestion
This page provides a guide explaining the breaking changes to help you
migrate your code from version 2 to version 3.
If we have missed anything, please open a `GitHub issue <https://github.com/zarr-developers/zarr-python/issues/new>`_ so we can impove this guide.
```

2024-12-30 17:37 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.copy_all`
According to https://github.com/zarr-developers/zarr-python/issues/2407#issuecomment-2494045572, copy and copy_all aren't going to be ported at all?

2025-01-01 17:00 UTC, d-v-b commented
In addition to a migration guide, what do people think about a "zarr v2 vs zarr v3" section that just describes how the semantics of v2 and v3 arrays are different? Not sure if that's in scope for this PR, or if it should be a separate effort, but it seems like the content is highly overlapping. I think the migration guide could link to the "v2 vs v3 concepts" section as needed when people have questions like "what's the logic behind with dimension separator handling zarr-python 3.xx"

2025-01-01 23:16 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  cloud object store)
nice suggestion. thanks.

2025-01-01 23:16 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +1. Disallow direct construction - use :func:`zarr.open_array` or :func:`zarr.create_array`
It is no longer possible (in the same way as it was before). I've clarified this.

2025-01-01 23:17 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +2. Deprecated most of the h5py compatibility methods. The following migration is suggested:
yes, they are drop in replacements.

2025-01-01 23:32 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +Dependencies Changes
done.

2025-01-01 23:34 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +Beyond the changes store interface, a number of deprecated stores were also removed in Zarr-Python 3:
Added additional details for all stores. 

tldr; n5/abs stores have external alternatives. the rest would require a custom store that zarr-python is unlikely to maintain unless they are added to the spec.

2025-01-01 23:34 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +
done.

2025-01-01 23:39 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
I disagree. The new runtime configuration object (`zarr.config`) collects a number of options that were present in v2 in other places.

2025-01-02 04:00 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +- The keyword argument ``zarr_version`` has been deprecated in favor of ``zarr_format``.
added notes clarifying this.

2025-01-02 04:03 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.copy_all`
Right, we haven't taken any action there yet though.

2025-01-02 04:03 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +2. Switched to a primarily Async interface.
expanded the language on the async store interface

2025-01-02 04:04 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +Ahead of the 3.0 release, we suggest projects that depend on Zarr-Python take the
Reworked this section. I still think a "getting ready" section is useful because projects will choose when to migrate based on their own situation.

2025-01-02 04:14 UTC, jhamman commented
I'm now reasonably happy with this as a first cut and suggest we do what we can to get this online ASAP. There are gaps that can be filled in as we go but this is much better than the current alternative (no migration guide).

---

to @d-v-b's https://github.com/zarr-developers/zarr-python/pull/2596#issuecomment-2567078867, let's add a zarr v2 vs v3 page elsewhere. I will not try to squeeze that into this PR.

to @dstansby's comment about specific migration paths for stuff in `zarr.hierarchy`, `zarr.attrs`, etc. I believe the statement in the docs reflects our position: 

> The following internal modules are being removed or significantly changed. If your application relies on imports from any of the below modules, you will need to either a) modify your application to no longer rely on these imports or b) vendor the parts of the specific modules that you need. 

I'm open to specific suggestions for how we could improve this wording.

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +   The following migration is suggested:
```suggestion
2. Most of the h5py compatibility methods are deprecated and will issue warnings if used.
   The following functions are drop in replacements that have the same signature and functionality:
```

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +- ``DBMStore``
```suggestion
The following stores have been removed altogether. Users who need these stores
will have to implement their own version in zarr-python v3.

- ``DBMStore``
```

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
Ah I didn't realise - in that case, this should be expanded to explain how users migrate from the old zarr.config system to the new system.

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.Group.move` (:issue:`2108`)
It's a bit confusing that these say they're not ported, but are linked to functions in the API docs (which would imply they are implemented). Do they need removing from the API docs?

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +- The following options in the top-level API (i.e. creation and convenience functions in
```suggestion
- The following features (corresponding to function arguments to functions in
```

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * ``dimension_separator``
All of these, apart from `synchronizer`, aree both present, and documented as working in the [API docs for `zarr.api.asynchronous.create()`](https://zarr.readthedocs.io/en/latest/_autoapi/zarr/api/asynchronous/index.html#zarr.api.asynchronous.create). Does this mean they have been ported, or the docstrings in the API docs need fixing? (or something else?)

2025-01-02 14:23 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.copy_all`
Is the plan to eventually implement `copy` and `copy_all`, or not? Currently this PR implies yes, but https://github.com/zarr-developers/zarr-python/issues/2407#issuecomment-2494045572 implies no.

2025-01-02 14:45 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
there was not an "old zarr.config" system. Runtime parameters were scattered throughout the API.

2025-01-02 14:46 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.Group.move` (:issue:`2108`)
All of these exist as stubs in the library but currently raise a `NotImplementedError`

2025-01-02 14:47 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  * ``dimension_separator``
We chose to not break the function signature but instead to raise either an error or warning if these options were provided. So yes, they exist in the signature, but they cannot be used.

2025-01-02 14:57 UTC, dstansby requested changes
🙌 this is looking great! I left another round of review comments, and a couple of more general things:

- Near the top, language should be changed from (e.g.) "will be" to "has been", since these are changes that have now happened.
- Since zarr.sync has gone with no replacement, there should be a short section on how to do process and thread syncrhonization in v3 (if it is possible - if not, just a short bit explaining it's not possible should be added)

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +the following actions:
```suggestion
the following actions in order:
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +     vendor the parts of the specific modules that you need.
There's scope for much more descriptive and helpful info about what's changed/what's gone here. Specifically:

- `zarr.attrs` has moved to `zarr.core.attributes`
- `zarr.codecs` has gone, import from `numcodecs` instead
- `zarr.context` has gone, with no replacement
- `zarr.core.Array` has moved to `zarr.Array` (but see migration notes below on how the `Array` object has changed)
- `zarr.hierarchy.Group` has moved to `zarr.Group` (but see migration notes below on how the `Group` object has changed)
- `zarr.hierarchy.group` and `zarr.hierarchy.open_group` has moved to `zarr.group` and `zarr.open_group`
- `zarr.indexing` has moved to `zarr.core.indexing`
- `zarr.meta` has moved to `zarr.core.metadata.common`, `zarr.core.metadata.v2` and `zarr.core.metadata.v3`
- `zarr.storage` still exists, but <list of thinks that have changed or been deleted>
- `zarr.sync` has gone, with no replacement
- `zarr.util` has gone, with no replacement (since this was always intended to be internal helper code)
- `zarr.n5` has gone, see <link to other repo> for replacement

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  cloud object store)
```suggestion
  cloud object stores)
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +Zarr-Python 3 represents a major refactor of the Zarr-Python codebase. Some of the
```suggestion
Zarr-Python 3.0 represents a major refactor of the Zarr-Python codebase. Some of the
```
Or change 3.0 > 3 below - I'd have a soft preference for "3" over "3.0".

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +of significant breaking changes and pending deprecations.
```suggestion
of significant breaking changes and deprecations.
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +This page provides a guide highlighting the most notable changes to help you
```suggestion
This page provides a guide explaing breaking changes and deprecations to help you
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +:class:`zarr.Group` classes and the "top-level API" (e.g. :func:`zarr.open_array` and
There's a section lower down that explains how breaking changes have happened to `Array` and `Group`, which seems at odds to this statement that backwards compat has been maintained. I'd be pro removing the "Compatibility target" section altogether to avoid this contradiction?

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +   (pre-releases are being published to PyPI weekly).
```suggestion
3. Test that your package works with v3.
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +The following sections provide details on the most important changes in Zarr-Python 3.
```suggestion
The following sections provide details on breaking changes in Zarr-Python 3.
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +Some of the biggest changes in Zarr-Python 3 are found in the ``Store`` class. The most
```suggestion
The most
```

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
Is there an example of code that someone would write in v2, which they now have to use the configuration system for instead? I think should be the measure of if something should go in the migration guide or not.

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.Group.move` (:issue:`2108`)
Should we remove them from the API docs then, so the docs don't give a misleading impression they exist?

2025-01-02 14:57 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * ``dimension_separator``
👍 I will open an issue to fix the API docs for these then

2025-01-02 14:58 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +  * ``dimension_separator``
Would be good to alkso note on this page that they exist in function signatures, but raise errors or warnings.

2025-01-03 15:45 UTC, jhamman commented
I'm going to wrap this up today. Fixing conflicts and resolving the final comments.

2025-01-03 17:16 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +Zarr-Python 3 represents a major refactor of the Zarr-Python codebase. Some of the
changed to 3 in most places except where specifically referring to the 3.0 release.

2025-01-03 17:26 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  * ``dimension_separator``
done.

2025-01-03 17:50 UTC, dstansby requested changes
These previous comments still need resolving somehow

- https://github.com/zarr-developers/zarr-python/pull/2596/files#r1900951361
- https://github.com/zarr-developers/zarr-python/pull/2596/files#r1900946457
- https://github.com/zarr-developers/zarr-python/pull/2596/files#r1900958061
- https://github.com/zarr-developers/zarr-python/pull/2596/files#r1900919883

2025-01-03 19:45 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +  * :func:`zarr.Group.move` (:issue:`2108`)
No opinion on whether to keep them in the API docs.

2025-01-03 19:45 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +:class:`zarr.Group` classes and the "top-level API" (e.g. :func:`zarr.open_array` and
A number of people asked for this explanation so I'm keen to keep it, if you have ideas for how to sharpen it, feel free to suggest additional language.

2025-01-03 19:48 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +     vendor the parts of the specific modules that you need.
I did a version of this.

2025-01-03 19:51 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +:func:`zarr.open_group`).
```suggestion
The goals described above necessitated some breaking changes to the API (hence the
major version update), but where possible we have maintained backwards compatibility
with functions in the top-level ``zarr`` namespace (e.g. :func:`zarr.open_array` and :func:`zarr.open_group`).
```

2025-01-03 19:51 UTC, dstansby commented on docs/user-guide/v3_migration.rst
> +:class:`zarr.Group` classes and the "top-level API" (e.g. :func:`zarr.open_array` and
👍 I put a suggestion here: https://github.com/zarr-developers/zarr-python/pull/2596/files/9427b10cade59400810890237ff71a10118319ae#r1902114450

2025-01-03 19:52 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +There is a new configuration system based on `donfig <https://github.com/pytroll/donfig>`_,
removed the config section.

2025-01-03 19:54 UTC, jhamman commented on docs/user-guide/v3_migration.rst
> +:func:`zarr.open_group`).
We have also attempted to maintain backward compatibility for the Group/Array classes. Neither the top level API or the Array/Group classes hit 100% backward compatibility.

2025-01-03 21:22 UTC, dcherian approved these changes
LGTM. Didn't verify the correctness, just reviewed the text.

2025-01-03 21:40 UTC, merged