docs: add docs on extending zarr 3
zarr-developers/zarr-python pull request #2597
Opened 2024-12-29 23:17 UTC by jhamman

This PR seeds the "how to extend Zarr" page for Zarr 3. Additional sections to be added in follow up PRs for custom stores and buffers).

Notes for reviewers:
- This was split out from https://github.com/zarr-developers/zarr-python/pull/2568 and builds on https://github.com/zarr-developers/zarr-python/pull/2589.

Closes #1770

2024-12-30 12:00 UTC, dstansby requested changes
One definite change (marking `validate` as optional), feel free to take or leave the other suggestions

2024-12-30 12:00 UTC, dstansby commented on docs/user-guide/extending.rst
> +    This sections explains how custom codecs can be created for Zarr version 3. For Zarr
Also, worth moving this up nearer the top so folks see it before reading the whole article and then realise it's only for v3?

2024-12-30 12:06 UTC, normanrz commented on docs/user-guide/extending.rst
> +    Note that the extension mechanism for the Zarr version 3 is still under development.
Not really. There are a few stale discussions but not a recent one. We are discussing this in the ZSC at the moment and will write a blog post to capture the discussion early next year that we can then link to from here.

2025-01-02 13:57 UTC, dstansby approved these changes

2025-01-02 14:04 UTC, dstansby requested changes
Actually, doc build needs fixing

2025-01-02 17:46 UTC, d-v-b approved these changes

2025-01-02 17:52 UTC, merged